Add several improvements to check_graphite_metric
* Pass graphite url via parameter (avoid hardcoding urls)
* Stop using getopts for parameter parsing
* Allow long parameters
* Add nagios-style bad status code return (255)
* Add Hysteresis support
* Add debug support

diff --git a/check_graphite_metric b/check_graphite_metric
--- a/check_graphite_metric
+++ b/check_graphite_metric
@@ -19,10 +19,6 @@
 ## Returns UNKNOWN status if can't retreive values from graphite.
 ##
 
-# set this to your graphite settings. remove -u parameter for curl if you don't have http authentication
-CURL_OPTIONS="-s -u YOUR_HTTP_USER:YOUR_HTTP_PASSWORD"
-GRAPHITE_RENDER_URL="https://YOUR_NAGIOS_BASE_URL/render/"
-
 # Declare some defaults
 EXIT_NAGIOS_STATUS=-1
 CHECK_OUTPUT=""
@@ -31,6 +27,8 @@ DEFAULT_NULL_STATUS=3
 METRIC_HOST_MATCHSTRING="%HOST%"
 # default timeframe to check graphite for values
 GRAPHITE_FROM_VALUE="8minutes"
+# default needed curl options - allow special chars + silent + timeout 30 seconds
+CURL_OPTIONS="-g -s --max-time 30"
 # array to store metric names returned from graphite. used to keep graphite's response order
 declare -a RES_METRICS
 # assoc. array to store values for each metric. declared -A to iterate results and keep only the last not null value
@@ -41,36 +39,44 @@ HAS_HI_PARAMS=0
 
 # define exit functions for nagios
 exit_ok() {
-echo "OK - ${CHECK_OUTPUT}"
-exit 0
+	echo "OK - ${CHECK_OUTPUT}"
+	exit 0
 }
 exit_war() {
-echo "WARNING - ${CHECK_OUTPUT}"
-exit 1
+	echo "WARNING - ${CHECK_OUTPUT}"
+	exit 1
 }
 exit_cri() {
-echo "CRITICAL - ${CHECK_OUTPUT}"
-exit 2
+	echo "CRITICAL - ${CHECK_OUTPUT}"
+	exit 2
 }
 exit_unk() {
-echo "UNKNOWN - ${CHECK_OUTPUT}"
-exit 3
+	echo "UNKNOWN - ${CHECK_OUTPUT}"
+	exit 3
+}
+exit_bad() {
+	echo "OUT OF RANGE - ${CHECK_OUTPUT}"
+	exit 255
 }
 # May this also be the inline documentation :)
 show_usage() {
 cat << EOF
 Usage: $0 -w <warn_lvl_high> -c <crit_lvl_high> [-H host] -m <graphite_metric_substring>
--W [value]   : Value threshold to alert as warning when graphite goes above it (hi level)
--C [value]   : Value threshold to alert as critical when graphite goes above it (hi/hi level)
--w [value]   : (Optional) Lower warning value threshold (lo level) Ignored if absent.
--c [value]   : (Optional) Lower critical value threshold (lo/lo level) Ignored if absent.
--H [host]    : (Optional) Host string in the format dc-NNN. If present, it will be replaced in the graphite metric.
--f [time]    : (Optional) Graphite-formatted time frame to check the metric for, to append to "&from=-" on the url. Defaults to "${GRAPHITE_FROM_VALUE}".
--m [metric]  : Graphite metric to be checked for values. If -H is present it will replace any occurence of the string "${METRIC_HOST_MATCHSTRING}" here.
--n [code]    : (Optional) Return specified status [OK|WARN|CRIT|UNK|0|1|2|3] when graphite gives NULL values only. Defaults to "UNK|3"
--t [minutes] : (Optional) Set MINUTES threshold for metric inspection (e.g.: -t 5 --> checks metric values for 5 minutes in the past). Defaults to "8"
--q           : Quiet output. Returns only the status, and values only if the status is critical or warning.
--h           : Show usage.
+-g|--graphite_url [url]  : Url (base) where graphite lives
+-G|--graphite_auth [u:p] : User / password to authenticate into graphite (http auth)
+-W|--warn_high [value]   : Value threshold to alert as warning when graphite goes above it (hi level)
+-C|--crit_high [value]   : Value threshold to alert as critical when graphite goes above it (hi/hi level)
+-w|--warn_low [value]    : (Optional) Lower warning value threshold (lo level) Ignored if absent.
+-c|--crit_low [value]    : (Optional) Lower critical value threshold (lo/lo level) Ignored if absent.
+-H|--host [host]         : (Optional) Host string in the format dc-NNN. If present, it will be replaced in the graphite metric.
+-m|--metric [metric]     : Graphite metric to be checked for values. If -H is present it will replace any occurence of the string "${METRIC_HOST_MATCHSTRING}" here.
+-n|--null_returns [code] : (Optional) Return specified status [OK|WARN|CRIT|UNK|0|1|2|3] when graphite gives NULL values only. Defaults to "UNK|3"
+-y|--hyst_warn [value]   : (Optional) Hysteresis for the warning level - how much value should change to turn off Warning
+-Y|--hyst_crit [value]   : (Optional) Hysteresis for the critical level - how much value should change to turn off Error
+-t|--timeframe [minutes] : (Optional) Set MINUTES threshold for metric inspection (e.g.: -t 5 --> checks metric values for 5 minutes in the past). Defaults to "8"
+-q|--quiet               : Quiet output. Returns only the status, and values only if the status is critical or warning.
+-h|--help                : Show usage.
+-d|--debug               : enable debug.
 Example:
 $0 -W 20 -C 40 -m "eu-002.cacti_propulsor.cacti_propulsor_cpu-0*.cpu_usage"
 WARNING - eu-002.cacti_propulsor.cacti_propulsor_cpu-02.cpu_usage=30.3966666667; eu-002.cacti_propulsor.cacti_propulsor_cpu-01.cpu_usage=22.8726666667; eu-002.cacti_propulsor.cacti_propulsor_cpu-03.cpu_usage=29.4873333333; eu-002.cacti_propulsor.cacti_propulsor_cpu-04.cpu_usage=27.258;
@@ -78,35 +84,62 @@ WARNING - eu-002.cacti_propulsor.cacti_propulsor_cpu-02.cpu_usage=30.3966666667;
 EOF
 }
 
-while getopts ":W:C:w:c:m:H:f:n:t:qh" OPT ; do
-	case "${OPT}" in
-	W)
-		WARN_LVL_HIGH=${OPTARG}
+check_status() {
+	local METRIC="${1}"
+	local ADDITION_CRIT="${2:-0}"
+	local ADDITION_WARN="${3:-0}"
+	local STATUS="0"
+	if [ $HAS_LO_PARAMS -eq 2 ] ; then
+		awk "BEGIN {exit !(${RES_VALUES["$METRIC"]} < ($WARN_LVL_LOW + $ADDITION_WARN))}" && STATUS=1
+		awk "BEGIN {exit !(${RES_VALUES["$METRIC"]} < ($CRIT_LVL_LOW + $ADDITION_CRIT))}" && STATUS=2
+	fi
+	if [ $HAS_HI_PARAMS -eq 2 ] ; then
+		awk "BEGIN {exit !(${RES_VALUES["$METRIC"]} > ($WARN_LVL_HIGH - ${ADDITION_WARN}))}" && STATUS=1
+		awk "BEGIN {exit !(${RES_VALUES["$METRIC"]} > ($CRIT_LVL_HIGH - ${ADDITION_CRIT}))}" && STATUS=2
+	fi
+	echo ${STATUS}
+}
+
+while (( "$#" )) ; do
+	case "${1}" in
+	-g|--graphite_url)
+		GRAPHITE_RENDER_URL="${2}/render/"
+		shift
+	;;
+	-G|--graphite_auth)
+		CURL_OPTIONS="${CURL_OPTIONS} -k -u ${2}"
+		shift
+	;;
+	-W|--warn_high)
+		WARN_LVL_HIGH=${2}
 		(( ++HAS_HI_PARAMS ))
+		shift
 	;;
-	C)
-		CRIT_LVL_HIGH=${OPTARG}
+	-C|--crit_high)
+		CRIT_LVL_HIGH=${2}
 		(( ++HAS_HI_PARAMS ))
+		shift
 	;;
-	w)
-		WARN_LVL_LOW=${OPTARG}
+	-w|--warn_low)
+		WARN_LVL_LOW=${2}
 		(( ++HAS_LO_PARAMS ))
+		shift
 	;;
-	c)
-		CRIT_LVL_LOW=${OPTARG}
+	-c|--crit_low)
+		CRIT_LVL_LOW=${2}
 		(( ++HAS_LO_PARAMS ))
+		shift
 	;;
-	m)
-		METRIC_STRING=${OPTARG}
+	-m|--host)
+		METRIC_STRING=${2}
+		shift
 	;;
-	H)
-		HOST=${OPTARG}
+	-H|--metric)
+		HOST=${2}
+		shift
 	;;
-	f)
-		GRAPHITE_FROM_VALUE=${OPTARG}
-	;;
-    n)
-		case ${OPTARG^^} in
+	-n|--null_returns)
+		case ${2^^} in
 			OK|0)
 				DEFAULT_NULL_STATUS=0
 			;;
@@ -120,22 +153,35 @@ while getopts ":W:C:w:c:m:H:f:n:t:qh" OPT ; do
 				DEFAULT_NULL_STATUS=3
 			;;
 		esac
-    ;;
-    t)
-		GRAPHITE_FROM_VALUE="${OPTARG}minutes"
+		shift
 	;;
-    q)
-        QUIET_OUTPUT=1
-    ;;
-	h)
+	-y|--hyst_warn)
+		HYSTERESIS_WARN=${2}
+		shift
+	;;
+	-Y|--hyst_crit)
+		HYSTERESIS_CRIT=${2}
+		shift
+	;;
+	-t|--timeframe)
+		GRAPHITE_FROM_VALUE="${2}minutes"
+		shift
+	;;
+	-q|--quiet)
+		QUIET_OUTPUT=1
+	;;
+	-d|--debug)
+		set -x
+	;;
+	-h|--help)
 		show_usage
 		exit 0
 	;;
 	*)
-		CHECK_OUTPUT="Can't parse parameters"
-		exit_unk
+		# silently ignore unknown parameters rather than rant about it and exit
 	;;
 	esac
+	shift
 done
 
 # build base curl options for querying graphite. build the target metric passed as parameter over it
@@ -144,25 +190,36 @@ GRAPHITE_QUERY_BASE="${GRAPHITE_RENDER_URL}?format=raw&from=-${GRAPHITE_FROM_VAL
 # make sure we have all the necessary parameters
 case $HAS_LO_PARAMS in
 	1)
-		CHECK_OUTPUT="Missing low level parameters. Passed -w=${WARN_LVL_LOW} -c=${CRIT_LVL_LOW}"
-		exit_unk
+		if [ -z ${WARN_LVL_LOW} ] ; then
+			# Default warning level to critical if not given
+			WARN_LVL_LOW=${CRIT_LVL_LOW}
+			(( ++HAS_LO_PARAMS ))
+		else
+			CHECK_OUTPUT="Missing CRITICAL (low) level parameter. Passed -w=${WARN_LVL_LOW} -c=${CRIT_LVL_LOW}"
+			exit_bad
+		fi
 	;;
 	2)
 		if `awk "BEGIN {exit !(${WARN_LVL_LOW} < ${CRIT_LVL_LOW})}"` ; then
 			CHECK_OUTPUT="Low Warning threshold cannot be below critical threshold. Passed -w=${WARN_LVL_LOW} -c=${CRIT_LVL_LOW}"
-			exit_unk
+			exit_bad
 		fi
 	;;
 esac
 case $HAS_HI_PARAMS in
 	1)
-		CHECK_OUTPUT="Missing high level parameters. Passed -W=${WARN_LVL_HIGH} -C=${CRIT_LVL_HIGH}"
-		exit_unk
+		if [ -z ${WARN_LVL_HIGH} ] ; then
+			WARN_LVL_HIGH=${CRIT_LVL_HIGH}
+			(( ++HAS_HI_PARAMS ))
+		else
+			CHECK_OUTPUT="Missing CRITICAL (high) level parameter. Passed -W=${WARN_LVL_HIGH} -C=${CRIT_LVL_HIGH}"
+			exit_bad
+		fi
 	;;
 	2)
 		if `awk "BEGIN {exit !(${WARN_LVL_HIGH} > ${CRIT_LVL_HIGH})}"` ; then
 			CHECK_OUTPUT="High Warning threshold cannot be over critical threshold. Passed -W=${WARN_LVL_HIGH} -C=${CRIT_LVL_HIGH}"
-			exit_unk
+			exit_bad
 		fi
 	;;
 esac
@@ -171,35 +228,34 @@ esac
 [ "$HOST" != "" ] && METRIC_STRING=$(sed "s/$METRIC_HOST_MATCHSTRING/$HOST/g" <<< $METRIC_STRING)
 
 # Run query against graphite and store last non-none values on the array
-for GRAPHITE_OUT in $(curl ${CURL_OPTIONS} ${GRAPHITE_QUERY_BASE}${METRIC_STRING} | sed 's/ //g') ; do
-        if [ "${GRAPHITE_METRIC:0:1}" = "<" ] ; then
-                GLOBAL_STATE=3
-                CHECK_OUTPUT="Graphite returned an error, check your metric: ${METRIC_STRING}"
-                exit_unk
-        fi
-	GRAPHITE_METRIC=$(cut -f1 -d\| <<< $GRAPHITE_OUT | sed  's/,[0-9]*,[0-9]*,[0-9]*$//')
+CURL_URI="${GRAPHITE_QUERY_BASE}${METRIC_STRING}"
+for GRAPHITE_OUT in $(curl ${CURL_OPTIONS} ${CURL_URI} | sed 's/ //g') ; do
+	if [[ "${GRAPHITE_OUT:0:1}" =~ ^\<.*|^\{.* ]] ; then
+		GLOBAL_STATE=3
+		CHECK_OUTPUT="Graphite returned an error, check your metric: ${METRIC_STRING}"
+		exit_unk
+	fi
+	GRAPHITE_METRIC=$(cut -f1 -d\| <<< $GRAPHITE_OUT | sed 's/,[0-9]*,[0-9]*,[0-9]*$//')
 	RES_METRICS+=("$GRAPHITE_METRIC")
 	for GRAPHITE_VALUE in $(cut -f2 -d\| <<< $GRAPHITE_OUT | sed 's/,/ /g') ; do
 		[ "${GRAPHITE_VALUE,,}" != "none" ] && RES_VALUES[${GRAPHITE_METRIC}]=${GRAPHITE_VALUE}
 	done
 done
 
+PREV_STATUS=${NAGIOS_LASTSERVICESTATEID:-0}
 if [ ${#RES_VALUES[@]} -eq 0 ] ; then
 	EXIT_NAGIOS_STATUS=$DEFAULT_NULL_STATUS
 	if [ ${DEFAULT_NULL_STATUS} -eq 3 ] ; then CHECK_OUTPUT="Graphite query ${METRIC_STRING} returned nothing." ; fi
 else
 	for METRIC in ${RES_METRICS[*]} ; do
 		METRIC_STATUS=0
-		if [[ "" == "${RES_VALUES["$METRIC"]}" ]] ; then 
+		if [[ "" == "${RES_VALUES["$METRIC"]}" ]] ; then
 			METRIC_STATUS=$DEFAULT_NULL_STATUS
 		else
-			if [ $HAS_LO_PARAMS -eq 2 ] ; then
-				awk "BEGIN {exit !(${RES_VALUES["$METRIC"]} < $WARN_LVL_LOW)}" && METRIC_STATUS=1
-				awk "BEGIN {exit !(${RES_VALUES["$METRIC"]} < $CRIT_LVL_LOW)}" && METRIC_STATUS=2
-			fi
-			if [ $HAS_HI_PARAMS -eq 2 ] ; then
-				awk "BEGIN {exit !(${RES_VALUES["$METRIC"]} > $WARN_LVL_HIGH)}" && METRIC_STATUS=1
-				awk "BEGIN {exit !(${RES_VALUES["$METRIC"]} > $CRIT_LVL_HIGH)}" && METRIC_STATUS=2
+			if [[ ! -z ${HYSTERESIS_CRIT} && ${PREV_STATUS} == 2 ]] || [[ ! -z ${HYSTERESIS_WARN} && ${PREV_STATUS} == 1 ]]; then
+				METRIC_STATUS=$(check_status "${METRIC}" "${HYSTERESIS_CRIT}" "${HYSTERESIS_WARN}")
+			else
+				METRIC_STATUS=$(check_status "${METRIC}" 0)
 			fi
 		fi
 		[ $METRIC_STATUS -gt $EXIT_NAGIOS_STATUS ] && EXIT_NAGIOS_STATUS=$METRIC_STATUS
